# Generated by Django 4.1.3 on 2022-12-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.brands', verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
