# Generated by Django 4.1.3 on 2022-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='slug',
            field=models.CharField(default=None, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
