# Generated by Django 4.1.3 on 2022-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brands_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
