# Generated by Django 4.1.3 on 2022-12-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_whishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhishList',
            new_name='WishList',
        ),
    ]
