# Generated by Django 4.1.3 on 2022-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_comments_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN PROCESSING', 'In processing'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('TAKEN FROM MAIL', 'Taken from mail')], default='IN PROCESSING', max_length=15, verbose_name='Статус заказа')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('mobile', models.CharField(max_length=30, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Штат')),
                ('zip_code', models.IntegerField(max_length=30, verbose_name='Zip Code')),
                ('shipping_cost', models.CharField(max_length=150, verbose_name='Цена доставки')),
                ('grand_total', models.CharField(max_length=150, verbose_name='Сумма заказа')),
            ],
        ),
    ]
