# Generated by Django 4.1.3 on 2022-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('PAYONEER', 'Payoneer'), ('CHECK PAYMENT', 'Check Payment'), ('DIRECT BANK TRANSFER', 'Direct Bank Transfer'), ('CACH ON DELIVERY', 'Cash on Delivery')], default='PAYPAL', max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN PROCESSING', 'In processing'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('TAKEN FROM MAIL', 'Taken from mail')], default='IN PROCESSING', max_length=35, verbose_name='Статус заказа'),
        ),
    ]
