# Generated by Django 4.1.3 on 2022-12-10 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_made_order',
            field=models.ManyToManyField(related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
    ]
