# Generated by Django 4.1.3 on 2022-12-12 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_made_order',
        ),
        migrations.AddField(
            model_name='order',
            name='user_made_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
